# Site settings
title: npat's musings
email: npat@efault.net
description: > # this means to ignore newlines until "baseurl:"
  Random musings about the life, the internet, and everything. Usually
  incredibly boring, nerdy stuff. Consume at you own risk (or don't).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://npat-efault.github.io" # the base hostname & protocol for your site
twitter_username: npat
github_username:  npat-efault

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    disable: true
